name: Deploy
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f Dockerfile --tag cr.visra.ge/hookshandler
    - name: Docker Push
      run: docker push cr.visra.ge/hookshandler
